// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4yNtBzV6559NSzCdOCtzREs4Iq6CKUM',
    appId: '1:82654456662:web:543c57441ff6e5747b44f7',
    messagingSenderId: '82654456662',
    projectId: 'finanzas-personales-1563d',
    authDomain: 'finanzas-personales-1563d.firebaseapp.com',
    storageBucket: 'finanzas-personales-1563d.firebasestorage.app',
    measurementId: 'G-PBS62B5GRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZ8IlAKm5Y4ppZX1vjQY8KtQi7INtEO0',
    appId: '1:82654456662:android:08d5d425229398737b44f7',
    messagingSenderId: '82654456662',
    projectId: 'finanzas-personales-1563d',
    storageBucket: 'finanzas-personales-1563d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC98v35fNr1UpfvY62_kZMMaWLzcA0Lyrc',
    appId: '1:82654456662:ios:fdbeb03ff5c435557b44f7',
    messagingSenderId: '82654456662',
    projectId: 'finanzas-personales-1563d',
    storageBucket: 'finanzas-personales-1563d.firebasestorage.app',
    iosBundleId: 'com.example.finanzasPersonales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC98v35fNr1UpfvY62_kZMMaWLzcA0Lyrc',
    appId: '1:82654456662:ios:fdbeb03ff5c435557b44f7',
    messagingSenderId: '82654456662',
    projectId: 'finanzas-personales-1563d',
    storageBucket: 'finanzas-personales-1563d.firebasestorage.app',
    iosBundleId: 'com.example.finanzasPersonales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG4yNtBzV6559NSzCdOCtzREs4Iq6CKUM',
    appId: '1:82654456662:web:37abe5b6ad3e9df47b44f7',
    messagingSenderId: '82654456662',
    projectId: 'finanzas-personales-1563d',
    authDomain: 'finanzas-personales-1563d.firebaseapp.com',
    storageBucket: 'finanzas-personales-1563d.firebasestorage.app',
    measurementId: 'G-KJHDE0MVEQ',
  );
}
